package view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class app {
		private JPanel panelApp=new JPanel(new BorderLayout());
		public JTabbedPane tab=new JTabbedPane(JTabbedPane.TOP);
		private JPanel panelClientes=new JPanel(new BorderLayout());
		private JPanel panelOesteCli=new JPanel(new BorderLayout());
		private JPanel panelDatosCli=new JPanel(new GridBagLayout());
		private GridBagConstraints c=new GridBagConstraints();
		private JLabel labelBuscarCli=new JLabel("BUSCAR CLIENTE");
		private JLabel labelNombreCli=new JLabel("NOMBRE");
		public JTextField txtNombreCli=new JTextField(15);
		private JLabel labelApellidoCli=new JLabel("APELLIDO");
		public JTextField txtApellidoCli=new JTextField(15);
		public JButton btnBuscarCli=new JButton("BUSCAR");
		public JButton btnDeshacerCli=new JButton("DESHACER");
		private JPanel panelEsteCli=new JPanel(new BorderLayout());
		private JPanel panelTablaCli=new JPanel(new BorderLayout());
		private JPanel panelBotonesCli=new JPanel(new BorderLayout());
		private String []columnas= {"DNI","NOMBRE","APELLIDO","TELEFONO","MAIL","CONTRASEÑA"};
		public DefaultTableModel modeloCli=new DefaultTableModel(columnas,0);
		public JTable tablaCli=new JTable(modeloCli);
		private JScrollPane scrollPanelCli;
		private JPanel panelBotonesCli1=new JPanel(new FlowLayout(FlowLayout.CENTER,50,0));
		public JButton btnSalirCli=new JButton("SALIR");
		public JButton btnGenerarXMLCli=new JButton("Generar XML");
		public JButton btnCrearCli=new JButton("CREAR");
		public JButton btnModificarCli=new JButton("MODIFICAR");
		public JButton btnEliminarCli=new JButton("ELIMINAR");
		private JPanel panelActividades=new JPanel(new BorderLayout());
		private JPanel panelOesteAct=new JPanel(new BorderLayout());
		private JPanel panelDatosAct=new JPanel(new GridBagLayout());
		private GridBagConstraints d=new GridBagConstraints();
		private JLabel labelBuscarAct=new JLabel("BUSCAR CLIENTE");
		private JLabel labelNombreAct=new JLabel("NOMBRE");
		public JTextField txtNombreAct=new JTextField(15);
		private JLabel labelApellidoAct=new JLabel("APELLIDO");
		public JTextField txtApellidoAct=new JTextField(15);
		public JButton btnBuscarAct=new JButton("BUSCAR");
		public JButton btnDeshacerAct=new JButton("DESHACER");
		private JPanel panelEsteAct=new JPanel(new BorderLayout());
		private JPanel panelTablaAct=new JPanel(new BorderLayout());
		private JPanel panelBotonesAct=new JPanel(new BorderLayout());
		private String []columnas1= {"DNI","NOMBRE","APELLIDO","TELEFONO","MAIL","CONTRASEÑA"};
		public DefaultTableModel modeloAct=new DefaultTableModel(columnas,0);
		public JTable tablaAct=new JTable(modeloAct);
		private JScrollPane scrollPanelAct;
		private JPanel panelBotonesAct1=new JPanel(new FlowLayout(FlowLayout.CENTER,50,0));
		public JButton btnSalirAct=new JButton("SALIR");
		public JButton btnGenerarXMLAct=new JButton("Generar XML");
		public JButton btnCrearAct=new JButton("CREAR");
		public JButton btnModificarAct=new JButton("MODIFICAR");
		public JButton btnEliminarAct=new JButton("ELIMINAR");
		
	public void app(inicioDeSesion inicio) {
		
		inicio.panelContenedor.add(panelApp,"app");
		inicio.carta.show(inicio.panelContenedor, "app");
		panelClientes.setBackground(Color.ORANGE);
		panelApp.setBackground(Color.ORANGE);
		panelDatosCli.setBackground(Color.ORANGE);
		tab.setBackground(Color.ORANGE);
		panelApp.add(tab);
		tab.addTab("Clientes", panelClientes);
		panelClientes.add(panelOesteCli, BorderLayout.WEST);
		panelOesteCli.setBackground(Color.ORANGE);
		panelOesteCli.setBorder(new EmptyBorder(1,10,10,10));
		panelDatosCli.setBackground(Color.WHITE);
		panelOesteCli.add(panelDatosCli);
		labelBuscarCli.setFont(new Font("Arial",Font.PLAIN,16));
		panelOesteCli.setPreferredSize(new Dimension(300,0));
		c.gridx=0;
		c.gridy=0;
		c.insets=new Insets(10,0,40,0);
		panelDatosCli.add(labelBuscarCli,c);
		labelBuscarCli.setBorder(new EmptyBorder(10,10,10,10));
		labelBuscarCli.setOpaque(true);
		labelBuscarCli.setForeground(Color.WHITE);
		labelBuscarCli.setBackground(Color.GRAY);;
		c.gridx=0;
		c.gridy=1;
		c.insets=new Insets(0,0,5,0);
		c.anchor=GridBagConstraints.WEST;
		panelDatosCli.add(labelNombreCli,c);
		c.gridx=0;
		c.gridy=2;
		c.insets=new Insets(0,0,40,0);
		panelDatosCli.add(txtNombreCli,c);
		c.gridx=0;
		c.gridy=3;
		c.insets=new Insets(0,0,5,0);
		panelDatosCli.add(labelApellidoCli,c);
		c.gridx=0;
		c.gridy=4;
		c.insets=new Insets(0,0,40,0);
		panelDatosCli.add(txtApellidoCli,c);
		c.gridx=0;
		c.gridy=5;
		c.insets=new Insets(0,1,60,1);
		panelDatosCli.add(btnBuscarCli,c);
		c.gridx=1;
		c.gridy=5;
		panelDatosCli.add(btnDeshacerCli,c);
		btnDeshacerCli.setEnabled(false);
		btnBuscarCli.setForeground(Color.WHITE);
		btnBuscarCli.setBackground(Color.GRAY);
		btnDeshacerCli.setForeground(Color.WHITE);
		btnDeshacerCli.setBackground(Color.GRAY);
		panelClientes.add(panelEsteCli,BorderLayout.EAST);
		panelEsteCli.setPreferredSize(new Dimension(675,0));
		panelTablaCli.setBackground(Color.ORANGE);
		panelEsteCli.add(panelTablaCli,BorderLayout.NORTH);
		panelClientes.add(panelBotonesCli,BorderLayout.SOUTH);
		panelTablaCli.setPreferredSize(new Dimension(0,500));
		panelBotonesCli.setPreferredSize(new Dimension(0,50));
		panelTablaCli.setBackground(Color.ORANGE);
		panelBotonesCli.setBackground(Color.ORANGE);
		panelTablaCli.add(tablaCli);
		tablaCli.setVisible(true);
		scrollPanelCli=new JScrollPane(tablaCli);
		panelTablaCli.add(scrollPanelCli);
		panelBotonesCli.setBorder(new EmptyBorder(10,10,10,10));
		panelBotonesCli.add(btnSalirCli, BorderLayout.WEST);
		panelBotonesCli.add(panelBotonesCli1,BorderLayout.EAST);
		panelBotonesCli1.setBackground(Color.ORANGE);
		panelBotonesCli1.add(btnGenerarXMLCli);
		panelBotonesCli1.add(btnCrearCli);
		panelBotonesCli1.add(btnModificarCli);
		btnModificarCli.setEnabled(false);
		panelBotonesCli1.add(btnEliminarCli);
		btnEliminarCli.setEnabled(false);
		
		//Panel de clientes
		tab.addTab("Actividades", panelActividades);
		panelActividades.setBackground(Color.ORANGE);
		panelActividades.add(panelOesteAct, BorderLayout.WEST);
		panelOesteAct.setBackground(Color.ORANGE);
		panelOesteAct.setBorder(new EmptyBorder(1,10,10,10));
		panelDatosAct.setBackground(Color.WHITE);
		panelOesteAct.add(panelDatosAct);
		labelBuscarAct.setFont(new Font("Arial",Font.PLAIN,16));
		panelOesteAct.setPreferredSize(new Dimension(300,0));
		d.gridx=0;
		d.gridy=0;
		d.insets=new Insets(10,0,40,0);
		panelDatosAct.add(labelBuscarAct,d);
		labelBuscarAct.setBorder(new EmptyBorder(10,10,10,10));
		labelBuscarAct.setOpaque(true);
		labelBuscarAct.setForeground(Color.WHITE);
		labelBuscarAct.setBackground(Color.GRAY);;
		d.gridx=0;
		d.gridy=1;
		d.insets=new Insets(0,0,5,0);
		d.anchor=GridBagConstraints.WEST;
		panelDatosAct.add(labelNombreAct,d);
		d.gridx=0;
		d.gridy=2;
		d.insets=new Insets(0,0,40,0);
		panelDatosAct.add(txtNombreAct,d);
		d.gridx=0;
		d.gridy=3;
		d.insets=new Insets(0,0,5,0);
		panelDatosAct.add(labelApellidoAct,d);
		d.gridx=0;
		d.gridy=4;
		d.insets=new Insets(0,0,40,0);
		panelDatosAct.add(txtApellidoAct,d);
		d.gridx=0;
		d.gridy=5;
		d.insets=new Insets(0,1,60,1);
		panelDatosAct.add(btnBuscarAct,d);
		d.gridx=1;
		d.gridy=5;
		panelDatosAct.add(btnDeshacerAct,c);
		btnDeshacerAct.setEnabled(false);
		btnBuscarAct.setForeground(Color.WHITE);
		btnBuscarAct.setBackground(Color.GRAY);
		btnDeshacerAct.setForeground(Color.WHITE);
		btnDeshacerAct.setBackground(Color.GRAY);
		panelActividades.add(panelEsteAct,BorderLayout.EAST);
		panelEsteAct.setPreferredSize(new Dimension(675,0));
		panelTablaAct.setBackground(Color.ORANGE);
		panelEsteAct.add(panelTablaAct,BorderLayout.NORTH);
		panelActividades.add(panelBotonesAct,BorderLayout.SOUTH);
		panelTablaAct.setPreferredSize(new Dimension(0,500));
		panelBotonesAct.setPreferredSize(new Dimension(0,50));
		panelTablaAct.setBackground(Color.ORANGE);
		panelBotonesAct.setBackground(Color.ORANGE);
		panelTablaAct.add(tablaAct);
		tablaAct.setVisible(true);
		scrollPanelAct=new JScrollPane(tablaAct);
		panelTablaAct.add(scrollPanelAct);
		panelBotonesAct.setBorder(new EmptyBorder(10,10,10,10));
		panelBotonesAct.add(btnSalirAct, BorderLayout.WEST);
		panelBotonesAct.add(panelBotonesAct1,BorderLayout.EAST);
		panelBotonesAct1.setBackground(Color.ORANGE);
		panelBotonesAct1.add(btnGenerarXMLAct);
		panelBotonesAct1.add(btnCrearAct);
		panelBotonesAct1.add(btnModificarAct);
		btnModificarAct.setEnabled(false);
		panelBotonesAct1.add(btnEliminarAct);
		
	}
}
