package view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class app {
		private JPanel panelApp=new JPanel(new BorderLayout());
		public JTabbedPane tab=new JTabbedPane(JTabbedPane.TOP);
		private JPanel panelClientes=new JPanel(new BorderLayout());
		private JPanel panelOesteCli=new JPanel(new BorderLayout());
		private JPanel panelDatosCli=new JPanel(new GridBagLayout());
		private GridBagConstraints c=new GridBagConstraints();
		private JLabel labelBuscarCli=new JLabel("BUSCAR CLIENTE");
		private JLabel labelNombreCli=new JLabel("NOMBRE");
		public JTextField txtNombreCli=new JTextField(15);
		private JLabel labelApellidoCli=new JLabel("APELLIDO");
		public JTextField txtApellidoCli=new JTextField(15);
		public JButton btnBuscarCli=new JButton("BUSCAR");
		public JButton btnDeshacerCli=new JButton("DESHACER");
		private JPanel panelEsteCli=new JPanel(new BorderLayout());
		private JPanel panelTablaCli=new JPanel(new BorderLayout());
		private JPanel panelBotonesCli=new JPanel(new BorderLayout());
		private String []columnas= {"DNI","NOMBRE","APELLIDO","TELEFONO","MAIL","CONTRASEÑA"};
		public DefaultTableModel modeloCli=new DefaultTableModel(columnas,0);
		public JTable tablaCli=new JTable(modeloCli);
		private JScrollPane scrollPanelCli;
		private JPanel panelBotonesCli1=new JPanel(new FlowLayout(FlowLayout.CENTER,50,0));
		public JButton btnSalirCli=new JButton("SALIR");
		public JButton btnGenerarXMLCli=new JButton("Generar XML");
		public JButton btnCrearCli=new JButton("CREAR");
		public JButton btnModificarCli=new JButton("MODIFICAR");
		public JButton btnEliminarCli=new JButton("ELIMINAR");
		
		//Excursiones//
		private JPanel panelExcursiones=new JPanel(new BorderLayout());
		private JPanel panelOesteEx=new JPanel(new BorderLayout());
		private JPanel panelDatosEx=new JPanel(new GridBagLayout());
		private GridBagConstraints d=new GridBagConstraints();
		private JLabel labelBuscarEx=new JLabel("BUSCAR CLIENTE");
		private JLabel labelNombreEx=new JLabel("NOMBRE");
		public JTextField txtNombreEx=new JTextField(15);
		private JLabel labelApellidoEx=new JLabel("APELLIDO");
		public JTextField txtApellidoEx=new JTextField(15);
		public JButton btnBuscarEx=new JButton("BUSCAR");
		public JButton btnDeshacerEx=new JButton("DESHACER");
		private JPanel panelEsteEx=new JPanel(new BorderLayout());
		private JPanel panelTablaEx=new JPanel(new BorderLayout());
		private JPanel panelBotonesEx=new JPanel(new BorderLayout());
		private String []columnas1= {"COD_RESERVA","NOMBRE_EMPRESA","AFORO","DIA","HORA","VISITA"};
		public DefaultTableModel modeloEx=new DefaultTableModel(columnas1,0);
		public JTable tablaEx=new JTable(modeloEx);
		private JScrollPane scrollPanelEx;
		private JPanel panelBotonesEx1=new JPanel(new FlowLayout(FlowLayout.CENTER,50,0));
		public JButton btnSalirEx=new JButton("SALIR");
		public JButton btnGenerarXMLEx=new JButton("Generar XML");
		public JButton btnCrearEx=new JButton("CREAR");
		public JButton btnModificarEx=new JButton("MODIFICAR");
		public JButton btnEliminarEx=new JButton("ELIMINAR");
		
		//Visitas//
		private JPanel panelVisitas=new JPanel(new BorderLayout());
		private JPanel panelOesteVi=new JPanel(new BorderLayout());
		private JPanel panelDatosVi=new JPanel(new GridBagLayout());
		private GridBagConstraints e=new GridBagConstraints();
		private JLabel labelBuscarVi=new JLabel("BUSCAR CLIENTE");
		private JLabel labelNombreVi=new JLabel("NOMBRE");
		public JTextField txtNombreVi=new JTextField(15);
		private JLabel labelApellidoVi=new JLabel("APELLIDO");
		public JTextField txtApellidoVi=new JTextField(15);
		public JButton btnBuscarVi=new JButton("BUSCAR");
		public JButton btnDeshacerVi=new JButton("DESHACER");
		private JPanel panelEsteVi=new JPanel(new BorderLayout());
		private JPanel panelTablaVi=new JPanel(new BorderLayout());
		private JPanel panelBotonesVi=new JPanel(new BorderLayout());
		private String []columnas2= {"COD_RESERVA","NOMBRE_EMPRESA","AFORO","DIA","HORA","VISITA"};
		public DefaultTableModel modeloVi=new DefaultTableModel(columnas2,0);
		public JTable tablaVi=new JTable(modeloVi);
		private JScrollPane scrollPanelVi;
		private JPanel panelBotonesVi1=new JPanel(new FlowLayout(FlowLayout.CENTER,50,0));
		public JButton btnSalirVi=new JButton("SALIR");
		public JButton btnGenerarXMLVi=new JButton("Generar XML");
		public JButton btnCrearVi=new JButton("CREAR");
		public JButton btnModificarVi=new JButton("MODIFICAR");
		public JButton btnEliminarVi=new JButton("ELIMINAR");
		
	public void app(inicioDeSesion inicio) {
		
		inicio.panelContenedor.add(panelApp,"app");
		inicio.carta.show(inicio.panelContenedor, "app");
		panelClientes.setBackground(Color.ORANGE);
		panelApp.setBackground(Color.ORANGE);
		panelDatosCli.setBackground(Color.ORANGE);
		tab.setBackground(Color.ORANGE);
		panelApp.add(tab);
		tab.addTab("Clientes", panelClientes);
		panelClientes.add(panelOesteCli, BorderLayout.WEST);
		panelOesteCli.setBackground(Color.ORANGE);
		panelOesteCli.setBorder(new EmptyBorder(10,10,10,10));
		panelDatosCli.setBackground(Color.WHITE);
		panelOesteCli.add(panelDatosCli);
		labelBuscarCli.setFont(new Font("Arial",Font.PLAIN,16));
		panelOesteCli.setPreferredSize(new Dimension(300,0));
		c.gridx=0;
		c.gridy=0;
		c.insets=new Insets(10,0,40,0);
		panelDatosCli.add(labelBuscarCli,c);
		labelBuscarCli.setBorder(new EmptyBorder(10,10,10,10));
		labelBuscarCli.setOpaque(true);
		labelBuscarCli.setForeground(Color.WHITE);
		labelBuscarCli.setBackground(Color.GRAY);;
		c.gridx=0;
		c.gridy=1;
		c.insets=new Insets(0,0,5,0);
		c.anchor=GridBagConstraints.WEST;
		panelDatosCli.add(labelNombreCli,c);
		c.gridx=0;
		c.gridy=2;
		c.insets=new Insets(0,0,40,0);
		panelDatosCli.add(txtNombreCli,c);
		c.gridx=0;
		c.gridy=3;
		c.insets=new Insets(0,0,5,0);
		panelDatosCli.add(labelApellidoCli,c);
		c.gridx=0;
		c.gridy=4;
		c.insets=new Insets(0,0,40,0);
		panelDatosCli.add(txtApellidoCli,c);
		c.gridx=0;
		c.gridy=5;
		c.insets=new Insets(0,1,60,1);
		panelDatosCli.add(btnBuscarCli,c);
		c.gridx=1;
		c.gridy=5;
		panelDatosCli.add(btnDeshacerCli,c);
		btnDeshacerCli.setEnabled(false);
		btnBuscarCli.setForeground(Color.WHITE);
		btnBuscarCli.setBackground(Color.GRAY);
		btnDeshacerCli.setForeground(Color.WHITE);
		btnDeshacerCli.setBackground(Color.GRAY);
		panelClientes.add(panelEsteCli,BorderLayout.EAST);
		panelEsteCli.setPreferredSize(new Dimension(675,0));
		panelTablaCli.setBackground(Color.ORANGE);
		panelEsteCli.add(panelTablaCli,BorderLayout.NORTH);
		panelClientes.add(panelBotonesCli,BorderLayout.SOUTH);
		panelTablaCli.setPreferredSize(new Dimension(0,500));
		panelBotonesCli.setPreferredSize(new Dimension(0,50));
		panelTablaCli.setBackground(Color.ORANGE);
		panelBotonesCli.setBackground(Color.ORANGE);
		panelTablaCli.add(tablaCli);
		tablaCli.setVisible(true);
		scrollPanelCli=new JScrollPane(tablaCli);
		panelTablaCli.add(scrollPanelCli);
		panelBotonesCli.setBorder(new EmptyBorder(10,10,10,10));
		panelBotonesCli.add(btnSalirCli, BorderLayout.WEST);
		panelBotonesCli.add(panelBotonesCli1,BorderLayout.EAST);
		panelBotonesCli1.setBackground(Color.ORANGE);
		panelBotonesCli1.add(btnGenerarXMLCli);
		panelBotonesCli1.add(btnCrearCli);
		panelBotonesCli1.add(btnModificarCli);
		btnModificarCli.setEnabled(false);
		panelBotonesCli1.add(btnEliminarCli);
		btnEliminarCli.setEnabled(false);
		
		//Panel de clientes
		tab.addTab("Excursiones", panelExcursiones);
		panelExcursiones.setBackground(Color.ORANGE);
		panelExcursiones.add(panelOesteEx, BorderLayout.WEST);
		panelOesteEx.setBackground(Color.ORANGE);
		panelOesteEx.setBorder(new EmptyBorder(10,10,10,10));
		panelDatosEx.setBackground(Color.WHITE);
		panelOesteEx.add(panelDatosEx);
		labelBuscarEx.setFont(new Font("Arial",Font.PLAIN,16));
		panelOesteEx.setPreferredSize(new Dimension(300,0));
		d.gridx=0;
		d.gridy=0;
		d.insets=new Insets(10,0,40,0);
		panelDatosEx.add(labelBuscarEx,d);
		labelBuscarEx.setBorder(new EmptyBorder(10,10,10,10));
		labelBuscarEx.setOpaque(true);
		labelBuscarEx.setForeground(Color.WHITE);
		labelBuscarEx.setBackground(Color.GRAY);;
		d.gridx=0;
		d.gridy=1;
		d.insets=new Insets(0,0,5,0);
		d.anchor=GridBagConstraints.WEST;
		panelDatosEx.add(labelNombreEx,d);
		d.gridx=0;
		d.gridy=2;
		d.insets=new Insets(0,0,40,0);
		panelDatosEx.add(txtNombreEx,d);
		d.gridx=0;
		d.gridy=3;
		d.insets=new Insets(0,0,5,0);
		panelDatosEx.add(labelApellidoEx,d);
		d.gridx=0;
		d.gridy=4;
		d.insets=new Insets(0,0,40,0);
		panelDatosEx.add(txtApellidoEx,d);
		d.gridx=0;
		d.gridy=5;
		d.insets=new Insets(0,1,60,1);
		panelDatosEx.add(btnBuscarEx,d);
		d.gridx=1;
		d.gridy=5;
		panelDatosEx.add(btnDeshacerEx,d);
		btnDeshacerEx.setEnabled(false);
		btnBuscarEx.setForeground(Color.WHITE);
		btnBuscarEx.setBackground(Color.GRAY);
		btnDeshacerEx.setForeground(Color.WHITE);
		btnDeshacerEx.setBackground(Color.GRAY);
		panelExcursiones.add(panelEsteEx,BorderLayout.EAST);
		panelEsteEx.setPreferredSize(new Dimension(675,0));
		panelTablaEx.setBackground(Color.ORANGE);
		panelEsteEx.add(panelTablaEx,BorderLayout.NORTH);
		panelExcursiones.add(panelBotonesEx,BorderLayout.SOUTH);
		panelTablaEx.setPreferredSize(new Dimension(0,500));
		panelBotonesEx.setPreferredSize(new Dimension(0,50));
		panelTablaEx.setBackground(Color.ORANGE);
		panelBotonesEx.setBackground(Color.ORANGE);
		panelTablaEx.add(tablaEx);
		tablaEx.setVisible(true);
		scrollPanelEx=new JScrollPane(tablaEx);
		panelTablaEx.add(scrollPanelEx);
		panelBotonesEx.setBorder(new EmptyBorder(10,10,10,10));
		panelBotonesEx.add(btnSalirEx, BorderLayout.WEST);
		panelBotonesEx.add(panelBotonesEx1,BorderLayout.EAST);
		panelBotonesEx1.setBackground(Color.ORANGE);
		panelBotonesEx1.add(btnGenerarXMLEx);
		panelBotonesEx1.add(btnCrearEx);
		panelBotonesEx1.add(btnModificarEx);
		btnModificarEx.setEnabled(false);
		panelBotonesEx1.add(btnEliminarEx);
		btnEliminarEx.setEnabled(false);
		
		//panel de visitas
		tab.addTab("Visitas",panelVisitas);
		panelVisitas.setBackground(Color.ORANGE);
		panelVisitas.add(panelOesteVi, BorderLayout.WEST);
		panelOesteVi.setBackground(Color.ORANGE);
		panelOesteVi.setBorder(new EmptyBorder(10,10,10,10));
		panelDatosVi.setBackground(Color.WHITE);
		panelOesteVi.add(panelDatosVi);
		labelBuscarVi.setFont(new Font("Arial",Font.PLAIN,16));
		panelOesteVi.setPreferredSize(new Dimension(300,0));
		e.gridx=0;
		e.gridy=0;
		e.insets=new Insets(10,0,40,0);
		panelDatosVi.add(labelBuscarVi,e);
		labelBuscarVi.setBorder(new EmptyBorder(10,10,10,10));
		labelBuscarVi.setOpaque(true);
		labelBuscarVi.setForeground(Color.WHITE);
		labelBuscarVi.setBackground(Color.GRAY);;
		e.gridx=0;
		e.gridy=1;
		e.insets=new Insets(0,0,5,0);
		e.anchor=GridBagConstraints.WEST;
		panelDatosVi.add(labelNombreVi,e);
		e.gridx=0;
		e.gridy=2;
		e.insets=new Insets(0,0,40,0);
		panelDatosVi.add(txtNombreVi,e);
		e.gridx=0;
		e.gridy=3;
		e.insets=new Insets(0,0,5,0);
		panelDatosVi.add(labelApellidoVi,e);
		e.gridx=0;
		e.gridy=4;
		e.insets=new Insets(0,0,40,0);
		panelDatosVi.add(txtApellidoVi,e);
		e.gridx=0;
		e.gridy=5;
		e.insets=new Insets(0,1,60,1);
		panelDatosVi.add(btnBuscarVi,e);
		e.gridx=1;
		e.gridy=5;
		panelDatosVi.add(btnDeshacerVi,e);
		btnDeshacerVi.setEnabled(false);
		btnBuscarVi.setForeground(Color.WHITE);
		btnBuscarVi.setBackground(Color.GRAY);
		btnDeshacerVi.setForeground(Color.WHITE);
		btnDeshacerVi.setBackground(Color.GRAY);
		panelVisitas.add(panelEsteVi,BorderLayout.EAST);
		panelEsteVi.setPreferredSize(new Dimension(675,0));
		panelTablaVi.setBackground(Color.ORANGE);
		panelEsteVi.add(panelTablaVi,BorderLayout.NORTH);
		panelVisitas.add(panelBotonesVi,BorderLayout.SOUTH);
		panelTablaVi.setPreferredSize(new Dimension(0,500));
		panelBotonesVi.setPreferredSize(new Dimension(0,50));
		panelTablaVi.setBackground(Color.ORANGE);
		panelBotonesVi.setBackground(Color.ORANGE);
		panelTablaVi.add(tablaVi);
		tablaVi.setVisible(true);
		scrollPanelVi=new JScrollPane(tablaVi);
		panelTablaVi.add(scrollPanelVi);
		panelBotonesVi.setBorder(new EmptyBorder(10,10,10,10));
		panelBotonesVi.add(btnSalirVi, BorderLayout.WEST);
		panelBotonesVi.add(panelBotonesVi1,BorderLayout.EAST);
		panelBotonesVi1.setBackground(Color.ORANGE);
		panelBotonesVi1.add(btnGenerarXMLVi);
		panelBotonesVi1.add(btnCrearVi);
		panelBotonesVi1.add(btnModificarVi);
		btnModificarVi.setEnabled(false);
		panelBotonesVi1.add(btnEliminarVi);
		btnEliminarVi.setEnabled(false);
	}
}
