package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

public class crearCliente {
	public JFrame frameCrearCli=new JFrame();
	private JPanel panelCliente=new JPanel(new BorderLayout());
	private JPanel panelCentro=new JPanel(new BorderLayout());
	private JPanel panelRegistrar1=new JPanel(new GridBagLayout());
	private GridBagConstraints c=new GridBagConstraints();
	private JLabel labelRegistrar=new JLabel("INTRODUCE LOS DATOS DEL NUEVO CLIENTE");
	private JLabel labelDni=new JLabel("DNI:* ");
	public JTextField txtDni=new JTextField(15);
	private JLabel labelNombre=new JLabel("Nombre:* ");
	public JTextField txtNombre=new JTextField(15);
	private JLabel labelApellido=new JLabel("Apellido:* ");
	public JTextField txtApellido=new JTextField(15);
	private JLabel labelTelefono=new JLabel("Teléfono:* ");
	public JTextField txtTelefono=new JTextField(15);
	private JLabel labelMail=new JLabel("Correo electronico:* ");
	public JTextField txtMail=new JTextField(15);
	private JLabel labelPass=new JLabel("Contraseña:* ");
	public JPasswordField txtPass=new JPasswordField(15);
	public JLabel labelNull=new JLabel("Registro incompleto, falta introducir datos");
	public JLabel labelIgual=new JLabel("El administrador ya está registrado");
	public JLabel labelLetras=new JLabel("No se puede introducir numeros en el telefono");
	public JLabel labelArroba=new JLabel("Introduce bien el mail, tiene que incluirse el @");
	public JButton btnCrear=new JButton("Crear cliente");
	public JButton btnPass=new JButton("Ver contraseña");
	private JPanel panelSur=new JPanel();
	public JButton btnVolver=new JButton("Volver");
	
	public void crearCli(inicioDeSesion inicio) {
		frameCrearCli.setTitle("Crear Cliente");
		panelCliente.add(panelCentro, BorderLayout.CENTER);
		panelCliente.setBackground(Color.ORANGE);
		panelCentro.add(panelRegistrar1);
		btnVolver.setBackground(Color.CYAN);
		labelNull.setForeground(Color.RED);
		labelIgual.setForeground(Color.RED);
		labelLetras.setForeground(Color.RED);
		labelArroba.setForeground(Color.RED);
		labelNull.setVisible(false);
		labelIgual.setVisible(false);
		labelLetras.setVisible(false);
		labelArroba.setVisible(false);
		btnCrear.setBackground(Color.CYAN);
		btnPass.setBackground(Color.CYAN);
		panelRegistrar1.setBackground(Color.ORANGE);
		c.gridwidth=2;
		c.gridx=0;
		c.gridy=0;
		c.insets=new Insets(0,30,30,30);
		panelRegistrar1.add(labelRegistrar,c);
		c.gridwidth=1;
		c.gridx=0;
		c.gridy=1;
		c.anchor=GridBagConstraints.EAST;
		c.insets=new Insets(0,10,10,10);
		panelRegistrar1.add(labelDni,c);
		c.gridx=1;
		c.gridy=1;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtDni,c);
		c.gridx=0;
		c.gridy=2;
		c.anchor=GridBagConstraints.EAST;
		panelRegistrar1.add(labelNombre,c);
		c.gridx=1;
		c.gridy=2;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtNombre,c);
		c.gridx=0;
		c.gridy=3;
		c.anchor=GridBagConstraints.EAST;
		panelRegistrar1.add(labelApellido,c);
		c.gridx=1;
		c.gridy=3;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtApellido,c);
		c.gridx=0;
		c.gridy=4;
		c.anchor=GridBagConstraints.EAST;
		panelRegistrar1.add(labelTelefono,c);
		c.gridx=1;
		c.gridy=4;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtTelefono,c);
		c.gridx=0;
		c.gridy=5;
		c.anchor=GridBagConstraints.EAST;
		panelRegistrar1.add(labelMail,c);
		c.gridx=1;
		c.gridy=5;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtMail,c);
		c.gridx=0;
		c.gridy=6;
		c.anchor=GridBagConstraints.EAST;
		panelRegistrar1.add(labelPass,c);
		c.gridx=1;
		c.gridy=6;
		c.anchor=GridBagConstraints.WEST;
		panelRegistrar1.add(txtPass,c);
		c.insets=new Insets(0,20,20,20);
		c.gridx=0;
		c.gridy=7;
		c.gridwidth=2;
		c.anchor=GridBagConstraints.CENTER;
		panelRegistrar1.add(labelNull,c);
		c.gridx=0;
		c.gridy=8;
		panelRegistrar1.add(labelIgual,c);
		c.gridx=0;
		c.gridy=8;
		panelRegistrar1.add(labelLetras,c);
		c.gridx=0;
		c.gridy=8;
		panelRegistrar1.add(labelArroba,c);
		c.gridwidth=1;
		c.gridx=0;
		c.gridy=9;
		c.insets=new Insets(0,0,0,0);
		panelRegistrar1.add(btnCrear,c);
		c.gridx=1;
		c.gridy=9;
		panelRegistrar1.add(btnPass,c);
		panelSur.setBackground(Color.ORANGE);
		panelSur.setBorder(new EmptyBorder(0,0,20,0));
		panelCliente.add(panelSur, BorderLayout.SOUTH);
		panelSur.add(btnVolver);
		frameCrearCli.add(panelCliente);
		frameCrearCli.setSize(400,400);
		frameCrearCli.setLocationRelativeTo(null);
		frameCrearCli.setVisible(true);
	}
}


