package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

public class modificarCliente {
	public JFrame frameModificar=new JFrame();
	private JPanel panelModificar=new JPanel(new BorderLayout());
	private JPanel panelCentro=new JPanel(new BorderLayout());
	private JPanel panelModificar1=new JPanel(new GridBagLayout());
	private GridBagConstraints c=new GridBagConstraints();
	private JLabel labelModificar;
	private JLabel labelDni=new JLabel("DNI:* ");
	public JTextField txtDni=new JTextField(15);
	public JLabel labelDniEr=new JLabel("El dni ya esta en uso");
	private JLabel labelNombre=new JLabel("Nombre:* ");
	public JTextField txtNombre=new JTextField(15);
	private JLabel labelApellido=new JLabel("Apellido:* ");
	public JTextField txtApellido=new JTextField(15);
	private JLabel labelTelefono=new JLabel("Teléfono:* ");
	public JTextField txtTelefono=new JTextField(15);
	private JLabel labelMail=new JLabel("Correo electronico:* ");
	public JTextField txtMail=new JTextField(15);
	private JLabel labelPass=new JLabel("Contraseña:* ");
	public JPasswordField txtPass=new JPasswordField(15);
	public JLabel labelNull=new JLabel("Registro incompleto, falta introducir datos");
	public JLabel labelIgual=new JLabel("El administrador ya está registrado");
	public JLabel labelLetras=new JLabel("No se puede introducir numeros en el telefono");
	public JLabel labelArroba=new JLabel("Introduce bien el mail, tiene que incluirse el @");
	public JButton btnModificar=new JButton("Modificar");
	public JButton btnPass=new JButton("Ver contraseña");
	private JPanel panelSur=new JPanel();
	public JButton btnVolver=new JButton("Volver");
	
	public void modificar(int num,String dni, app App) {
		frameModificar.setTitle("Modificar Cliente");
		frameModificar.add(panelModificar);
		panelModificar.add(panelCentro, BorderLayout.CENTER);
		panelModificar.setBackground(Color.ORANGE);
		panelCentro.add(panelModificar1);
		btnVolver.setBackground(Color.CYAN);
		labelNull.setForeground(Color.RED);
		labelIgual.setForeground(Color.RED);
		labelLetras.setForeground(Color.RED);
		labelArroba.setForeground(Color.RED);
		labelDniEr.setForeground(Color.RED);
		labelNull.setVisible(false);
		labelIgual.setVisible(false);
		labelLetras.setVisible(false);
		labelArroba.setVisible(false);
		labelDniEr.setVisible(false);
		btnModificar.setBackground(Color.CYAN);
		btnPass.setBackground(Color.CYAN);
		panelModificar1.setBackground(Color.ORANGE);
		c.gridwidth=2;
		c.gridx=0;
		c.gridy=0;
		c.insets=new Insets(0,30,30,30);
		labelModificar=new JLabel("Introduce los nuevos datos para la "+App.tablaCli.getValueAt(num, 0).toString());
		panelModificar1.add(labelModificar,c);
		c.gridwidth=1;
		c.gridx=0;
		c.gridy=1;
		c.anchor=GridBagConstraints.EAST;
		c.insets=new Insets(0,10,10,10);
		panelModificar1.add(labelDni,c);
		c.gridx=1;
		c.gridy=1;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtDni,c);
		c.gridx=0;
		c.gridy=2;
		c.anchor=GridBagConstraints.EAST;
		panelModificar1.add(labelNombre,c);
		c.gridx=1;
		c.gridy=2;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtNombre,c);
		c.gridx=0;
		c.gridy=3;
		c.anchor=GridBagConstraints.EAST;
		panelModificar1.add(labelApellido,c);
		c.gridx=1;
		c.gridy=3;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtApellido,c);
		c.gridx=0;
		c.gridy=4;
		c.anchor=GridBagConstraints.EAST;
		panelModificar1.add(labelTelefono,c);
		c.gridx=1;
		c.gridy=4;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtTelefono,c);
		c.gridx=0;
		c.gridy=5;
		c.anchor=GridBagConstraints.EAST;
		panelModificar1.add(labelMail,c);
		c.gridx=1;
		c.gridy=5;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtMail,c);
		c.gridx=0;
		c.gridy=6;
		c.anchor=GridBagConstraints.EAST;
		panelModificar1.add(labelPass,c);
		c.gridx=1;
		c.gridy=6;
		c.anchor=GridBagConstraints.WEST;
		panelModificar1.add(txtPass,c);
		c.insets=new Insets(0,20,20,20);
		c.gridx=0;
		c.gridy=7;
		c.gridwidth=2;
		c.anchor=GridBagConstraints.CENTER;
		panelModificar1.add(labelNull,c);
		c.gridx=0;
		c.gridy=8;
		panelModificar1.add(labelIgual,c);
		c.gridx=0;
		c.gridy=8;
		panelModificar1.add(labelLetras,c);
		c.gridx=0;
		c.gridy=8;
		panelModificar1.add(labelArroba,c);
		panelModificar1.add(labelDniEr,c);
		c.gridwidth=1;
		c.gridx=0;
		c.gridy=9;
		c.insets=new Insets(0,0,0,0);
		panelModificar1.add(btnModificar,c);
		c.gridx=1;
		c.gridy=9;
		panelModificar1.add(btnPass,c);
		panelSur.setBackground(Color.ORANGE);
		panelSur.setBorder(new EmptyBorder(0,0,20,0));
		panelModificar.add(panelSur, BorderLayout.SOUTH);
		panelSur.add(btnVolver);
		frameModificar.setLocationRelativeTo(null);
		frameModificar.setSize(500,400);
		frameModificar.setVisible(true);
	}
}
